/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Sale from '../sale';
import { ISaleData } from '../sale.data';
import {
  ISaleConfig,
  ISaleProps
} from '../sale.props.autogenerated';

const mockData: ISaleData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ISaleConfig = {
  showText: 'sale'
};

const mockActions = {};

describe('Sale', () => {
  let moduleProps: ISaleProps<ISaleData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ISaleProps<ISaleData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Sale {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
