/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaAccountData } from './wkea-account.data';
import { IWkeaAccountProps } from './wkea-account.props.autogenerated';

export interface IWkeaAccountViewProps extends IWkeaAccountProps<IWkeaAccountData> {
    orderHistory: React.ReactNode[]
    myProfile: React.ReactNode[]
    wishList: React.ReactNode[]
    address: React.ReactNode[]
}

/**
 *
 * WkeaAccount component
 * @extends {React.PureComponent<IWkeaAccountProps<IWkeaAccountData>>}
 */
class WkeaAccount extends React.PureComponent<IWkeaAccountProps<IWkeaAccountData>> {
    public render(): JSX.Element | null {
        const { slots: {orderHistory, myProfile, wishList, address} } = this.props

        return this.props.renderView({
            ...this.props,
            orderHistory: orderHistory && orderHistory[0],
            myProfile: myProfile && myProfile[0],
            wishList: wishList && wishList[0],
            address: address && address[0]
        });
    }
}

export default WkeaAccount;
