/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import WkeaHistory from '../wkea-history';
import { IWkeaHistoryData } from '../wkea-history.data';
import {
  IWkeaHistoryConfig,
  IWkeaHistoryProps
} from '../wkea-history.props.autogenerated';

const mockData: IWkeaHistoryData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IWkeaHistoryConfig = {
  showText: 'wkea-history'
};

const mockActions = {};

describe('WkeaHistory', () => {
  let moduleProps: IWkeaHistoryProps<IWkeaHistoryData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IWkeaHistoryProps<IWkeaHistoryData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <WkeaHistory {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
