/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IMyorderData } from './myorder.data';
import { IMyorderProps } from './myorder.props.autogenerated';

export interface IMyorderViewProps extends IMyorderProps<IMyorderData> {

}

/**
 *
 * Myorder component
 * @extends {React.PureComponent<IMyorderProps<IMyorderData>>}
 */
class Myorder extends React.PureComponent<IMyorderProps<IMyorderData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Myorder;
