/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaAboutData } from './wkea-about.data';
import { IWkeaAboutProps } from './wkea-about.props.autogenerated';

export interface IWkeaAboutViewProps extends IWkeaAboutProps<IWkeaAboutData> {

}

/**
 *
 * WkeaAbout component
 * @extends {React.PureComponent<IWkeaAboutProps<IWkeaAboutData>>}
 */
class WkeaAbout extends React.PureComponent<IWkeaAboutProps<IWkeaAboutData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaAbout;
