/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Myorder from '../myorder';
import { IMyorderData } from '../myorder.data';
import {
  IMyorderConfig,
  IMyorderProps
} from '../myorder.props.autogenerated';

const mockData: IMyorderData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IMyorderConfig = {
  showText: 'myorder'
};

const mockActions = {};

describe('Myorder', () => {
  let moduleProps: IMyorderProps<IMyorderData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IMyorderProps<IMyorderData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Myorder {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
