/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import IndexCarousel from '../index-carousel';
import { IIndexCarouselData } from '../index-carousel.data';
import {
  IIndexCarouselConfig,
  IIndexCarouselProps
} from '../index-carousel.props.autogenerated';

const mockData: IIndexCarouselData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IIndexCarouselConfig = {
  showText: 'index-carousel'
};

const mockActions = {};

describe('IndexCarousel', () => {
  let moduleProps: IIndexCarouselProps<IIndexCarouselData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IIndexCarouselProps<IIndexCarouselData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <IndexCarousel {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
