/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaFaqData } from './wkea-faq.data';
import { IWkeaFaqProps } from './wkea-faq.props.autogenerated';

export interface IWkeaFaqViewProps extends IWkeaFaqProps<IWkeaFaqData> {

}

/**
 *
 * WkeaFaq component
 * @extends {React.PureComponent<IWkeaFaqProps<IWkeaFaqData>>}
 */
class WkeaFaq extends React.PureComponent<IWkeaFaqProps<IWkeaFaqData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaFaq;
