/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaSupplierData } from './wkea-supplier.data';
import { IWkeaSupplierProps } from './wkea-supplier.props.autogenerated';

export interface IWkeaSupplierViewProps extends IWkeaSupplierProps<IWkeaSupplierData> {

}

/**
 *
 * WkeaSupplier component
 * @extends {React.PureComponent<IWkeaSupplierProps<IWkeaSupplierData>>}
 */
class WkeaSupplier extends React.PureComponent<IWkeaSupplierProps<IWkeaSupplierData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaSupplier;
