/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IOrdercenterData } from './ordercenter.data';
import { IOrdercenterProps } from './ordercenter.props.autogenerated';

export interface IOrdercenterViewProps extends IOrdercenterProps<IOrdercenterData> {

}

/**
 *
 * Ordercenter component
 * @extends {React.PureComponent<IOrdercenterProps<IOrdercenterData>>}
 */
class Ordercenter extends React.PureComponent<IOrdercenterProps<IOrdercenterData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Ordercenter;
