/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IHelpcenterData } from './helpcenter.data';
import { IHelpcenterProps } from './helpcenter.props.autogenerated';

export interface IHelpcenterViewProps extends IHelpcenterProps<IHelpcenterData> {

}

/**
 *
 * Helpcenter component
 * @extends {React.PureComponent<IHelpcenterProps<IHelpcenterData>>}
 */
class Helpcenter extends React.PureComponent<IHelpcenterProps<IHelpcenterData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Helpcenter;
