/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Test from '../test';
import { ITestData } from '../test.data';
import {
  ITestConfig,
  ITestProps
} from '../test.props.autogenerated';

const mockData: ITestData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ITestConfig = {
  showText: 'test'
};

const mockActions = {};

describe('Test', () => {
  let moduleProps: ITestProps<ITestData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ITestProps<ITestData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Test {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
