/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Ordercenter from '../ordercenter';
import { IOrdercenterData } from '../ordercenter.data';
import {
  IOrdercenterConfig,
  IOrdercenterProps
} from '../ordercenter.props.autogenerated';

const mockData: IOrdercenterData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IOrdercenterConfig = {
  showText: 'ordercenter'
};

const mockActions = {};

describe('Ordercenter', () => {
  let moduleProps: IOrdercenterProps<IOrdercenterData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IOrdercenterProps<IOrdercenterData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Ordercenter {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
