/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Joinus from '../joinus';
import { IJoinusData } from '../joinus.data';
import {
  IJoinusConfig,
  IJoinusProps
} from '../joinus.props.autogenerated';

const mockData: IJoinusData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IJoinusConfig = {
  showText: 'joinus'
};

const mockActions = {};

describe('Joinus', () => {
  let moduleProps: IJoinusProps<IJoinusData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IJoinusProps<IJoinusData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Joinus {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
