/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ISaleData } from './sale.data';
import { ISaleProps } from './sale.props.autogenerated';

export interface ISaleViewProps extends ISaleProps<ISaleData> {

}

/**
 *
 * Sale component
 * @extends {React.PureComponent<ISaleProps<ISaleData>>}
 */
class Sale extends React.PureComponent<ISaleProps<ISaleData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Sale;
