/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import IndexPerson from '../index-person';
import { IIndexPersonData } from '../index-person.data';
import {
  IIndexPersonConfig,
  IIndexPersonProps
} from '../index-person.props.autogenerated';

const mockData: IIndexPersonData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IIndexPersonConfig = {
  showText: 'index-person'
};

const mockActions = {};

describe('IndexPerson', () => {
  let moduleProps: IIndexPersonProps<IIndexPersonData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IIndexPersonProps<IIndexPersonData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <IndexPerson {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
