/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaServiceData } from './wkea-service.data';
import { IWkeaServiceProps } from './wkea-service.props.autogenerated';

export interface IWkeaServiceViewProps extends IWkeaServiceProps<IWkeaServiceData> {

}

/**
 *
 * WkeaService component
 * @extends {React.PureComponent<IWkeaServiceProps<IWkeaServiceData>>}
 */
class WkeaService extends React.PureComponent<IWkeaServiceProps<IWkeaServiceData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaService;
