
/**
 * Copyright (c) 2018 Microsoft Corporation
 * Modules Registration
 * THIS FILE IS AUTO-GENERATED - MANUAL MODIFICATIONS WILL BE LOST
 */

const universal = require('react-universal-component').default;

/**
 * Register all available modules
 */
export const registerAllModules = (requiredModules) => {
    let binding = { modules: {}, dataActions: {} };
    const { log, error }  = console;
    const detailedWebpackError = (msg, errorObject) => { error(msg); error(errorObject); process.env.NODE_ENV !== 'development' && error('Run in dev mode to see full list of errors'); process.exit(50); }
    const handleError = (modPath, errObject) => {
        detailedWebpackError('Error with path: ' + modPath, errObject);
    }
    if (requiredModules) {
        requiredModules = requiredModules.map((module) => module.toLowerCase());
    }
    const isNotRegistered = (moduleName) => {
        return !requiredModules || requiredModules.length <= 0 || requiredModules.findIndex((module) => module === moduleName) !== -1;
    };

    


    isNotRegistered('footer') && (binding.modules['footer'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
/* webpackMode: "eager" */
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/footer/footer'),
            {
                chunkName: () => 'partner-modules-footer-footer',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/footer/footer.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'footer',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/footer'
    });
            

    isNotRegistered('header') && (binding.modules['header'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
/* webpackMode: "eager" */
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/header/header'),
            {
                chunkName: () => 'partner-modules-header-header',
                ignoreBabelRename: true
            }
        ),
        $type: 'containerModule',
        dataActions: [{name:'accountInformation',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', runOn: 0},{name:'cart',  path:'@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', runOn: 0}],
        
        definitionPath: 'src/modules/header/header.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'header',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/header'
    });
            

    isNotRegistered('wkea') && (binding.modules['wkea'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
/* webpackMode: "eager" */
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/themes/wkea/wkea'),
            {
                chunkName: () => 'partner-themes-wkea-wkea',
                ignoreBabelRename: true
            }
        ),
        $type: 'themeModule',
        dataActions: [],
        
        definitionPath: 'src/themes/wkea/wkea.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        themeSettings: 'wkea.theme.settings.json',
        moduleDirectory: 'src/themes/wkea'
    });
            

    try {
        if (isNotRegistered('header')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer';
            let dataAction = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer');
            if (!dataAction.default) {
                throw new Error('Data action path does not have a default export');
            }
            if (!(dataAction.default.prototype.id && binding.dataActions[dataAction.default.prototype.id]) || !binding.dataActions[sanitizedActionPath]) {
                binding.dataActions[sanitizedActionPath] = dataAction;
            }
        }
    } catch(e) {
        binding.dataActions['@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer'] = undefined;
        handleError('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', e);
    }
    

    try {
        if (isNotRegistered('header')) {
            const sanitizedActionPath = '@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action';
            let dataAction = require('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action');
            if (!dataAction.default) {
                throw new Error('Data action path does not have a default export');
            }
            if (!(dataAction.default.prototype.id && binding.dataActions[dataAction.default.prototype.id]) || !binding.dataActions[sanitizedActionPath]) {
                binding.dataActions[sanitizedActionPath] = dataAction;
            }
        }
    } catch(e) {
        binding.dataActions['@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action'] = undefined;
        handleError('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', e);
    }
    

    
    return binding;
};