
/**
 * Copyright (c) 2018 Microsoft Corporation
 * Modules Registration
 * THIS FILE IS AUTO-GENERATED - MANUAL MODIFICATIONS WILL BE LOST
 */

const universal = require('react-universal-component').default;

/**
 * Register all available modules
 */
export const registerAllModules = (requiredModules) => {
    let binding = { modules: {}, dataActions: {} };
    const { log, error }  = console;
    const detailedWebpackError = (msg, errorObject) => { error(msg); error(errorObject); process.env.NODE_ENV !== 'development' && error('Run in dev mode to see full list of errors'); process.exit(50); }
    const handleError = (modPath, errObject) => {
        detailedWebpackError('Error with path: ' + modPath, errObject);
    }
    if (requiredModules) {
        requiredModules = requiredModules.map((module) => module.toLowerCase());
    }
    const isNotRegistered = (moduleName) => {
        return !requiredModules || requiredModules.length <= 0 || requiredModules.findIndex((module) => module === moduleName) !== -1;
    };

    try {


    isNotRegistered('breadcrumb') && (binding.modules['breadcrumb'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/breadcrumb/breadcrumb'),
            {
                chunkName: () => 'partner-modules-breadcrumb-breadcrumb',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'categoryHierarchy',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy', runOn: 0},{name:'categoryPaths',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-category-paths', runOn: 0},{name:'product',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant', runOn: 0}],
        
        definitionPath: 'src/modules/breadcrumb/breadcrumb.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'breadcrumb',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/breadcrumb'
    });
            

    isNotRegistered('buybox') && (binding.modules['buybox'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/buybox1/buybox'),
            {
                chunkName: () => 'partner-modules-buybox1-buybox',
                ignoreBabelRename: true
            }
        ),
        $type: 'containerModule',
        dataActions: [{name:'cart',  path:'@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', runOn: 0},{name:'customerInformation',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', runOn: 0},{name:'deliveryOptions',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-selected-variant', runOn: 0},{name:'orderTemplates',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview', runOn: 1},{name:'product',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant', runOn: 0},{name:'productAvailableQuantity',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-product-availabilities-for-selected-variant', runOn: 0},{name:'productDimensions',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-dimensions-for-selected-variant', runOn: 0},{name:'productPrice',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-price-for-selected-variant', runOn: 0},{name:'ratingsSummary',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-ratings-summary', runOn: 1},{name:'storeSelectorStateManager',  path:'@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action', runOn: 0},{name:'wishlists',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id', runOn: 0}],
        
        definitionPath: 'src/modules/buybox1/buybox.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'buybox',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/buybox1'
    });
            

    isNotRegistered('cart') && (binding.modules['cart'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/cart1/cart'),
            {
                chunkName: () => 'partner-modules-cart1-cart',
                ignoreBabelRename: true
            }
        ),
        $type: 'containerModule',
        dataActions: [{name:'cart',  path:'@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', runOn: 0},{name:'customerInformation',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', runOn: 0},{name:'deliveryOptions',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-cartlines', runOn: 0},{name:'featureState',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-feature-state', runOn: 0},{name:'orderTemplates',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview', runOn: 1},{name:'orgUnitLocations',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/search-org-unit-locations', runOn: 0},{name:'productAvailabilites',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-availabilities-cartlines', runOn: 0},{name:'products',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-products-in-active-cart', runOn: 0},{name:'storeSelectorStateManager',  path:'@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action', runOn: 0},{name:'wishlistItems',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-items-in-wishlist', runOn: 1},{name:'wishlists',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id', runOn: 1}],
        
        definitionPath: 'src/modules/cart1/cart.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'cart',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/cart1'
    });
            

    isNotRegistered('footer') && (binding.modules['footer'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/footer/footer'),
            {
                chunkName: () => 'partner-modules-footer-footer',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/footer/footer.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'footer',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/footer'
    });
            

    isNotRegistered('header') && (binding.modules['header'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/header/header'),
            {
                chunkName: () => 'partner-modules-header-header',
                ignoreBabelRename: true
            }
        ),
        $type: 'containerModule',
        dataActions: [{name:'accountInformation',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', runOn: 0},{name:'cart',  path:'@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', runOn: 0}],
        
        definitionPath: 'src/modules/header/header.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'header',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/header'
    });
            

    isNotRegistered('helpcenter') && (binding.modules['helpcenter'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/helpcenter/helpcenter'),
            {
                chunkName: () => 'partner-modules-helpcenter-helpcenter',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/helpcenter/helpcenter.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'helpcenter',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/helpcenter'
    });
            

    isNotRegistered('index-carousel') && (binding.modules['index-carousel'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/index-carousel/index-carousel'),
            {
                chunkName: () => 'partner-modules-index-carousel-index-carousel',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/index-carousel/index-carousel.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'index-carousel',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/index-carousel'
    });
            

    isNotRegistered('index-person-information') && (binding.modules['index-person-information'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/index-person-information/index-person-information'),
            {
                chunkName: () => 'partner-modules-index-person-information-index-person-information',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'accountInformation',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer', runOn: 0},{name:'cart',  path:'@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action', runOn: 0}],
        
        definitionPath: 'src/modules/index-person-information/index-person-information.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'index-person-information',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/index-person-information'
    });
            

    isNotRegistered('index-product') && (binding.modules['index-product'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/index-product/index-product'),
            {
                chunkName: () => 'partner-modules-index-product-index-product',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'products',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-simple-products', runOn: 0}],
        
        definitionPath: 'src/modules/index-product/index-product.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'index-product',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/index-product'
    });
            

    isNotRegistered('joinus') && (binding.modules['joinus'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/joinus/joinus'),
            {
                chunkName: () => 'partner-modules-joinus-joinus',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/joinus/joinus.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'joinus',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/joinus'
    });
            

    isNotRegistered('media-gallery') && (binding.modules['media-gallery'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/media-gallery/media-gallery'),
            {
                chunkName: () => 'partner-modules-media-gallery-media-gallery',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'mediaLocations',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-media-locations-by-id', runOn: 0},{name:'product',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant', runOn: 0}],
        
        definitionPath: 'src/modules/media-gallery/media-gallery.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'media-gallery',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/media-gallery'
    });
            

    isNotRegistered('navigation-menu') && (binding.modules['navigation-menu'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/navigation-menu1/navigation-menu'),
            {
                chunkName: () => 'partner-modules-navigation-menu1-navigation-menu',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'categories',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-categories-hierarchy', runOn: 0}],
        
        definitionPath: 'src/modules/navigation-menu1/navigation-menu.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'navigation-menu',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/navigation-menu1'
    });
            

    isNotRegistered('sale') && (binding.modules['sale'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/sale/sale'),
            {
                chunkName: () => 'partner-modules-sale-sale',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/sale/sale.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'sale',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/sale'
    });
            

    isNotRegistered('search') && (binding.modules['search'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/search/search'),
            {
                chunkName: () => 'partner-modules-search-search',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'searchState',  path:'@msdyn365-commerce-modules/search-utilities/dist/lib/search-state-data-action', runOn: 1}],
        
        definitionPath: 'src/modules/search/search.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'search',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/search'
    });
            

    isNotRegistered('search-result-container') && (binding.modules['search-result-container'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/search-result-container/search-result-container'),
            {
                chunkName: () => 'partner-modules-search-result-container-search-result-container',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [{name:'category',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category', runOn: 0},{name:'categoryHierarchy',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy', runOn: 0},{name:'featureProduct',  path:'@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant', runOn: 0},{name:'listPageState',  path:'modules/search-result-container/list-page-state', runOn: 0},{name:'products',  path:'modules/search-result-container/actions/get-full-products-by-collection', runOn: 0},{name:'refiners',  path:'modules/search-result-container/actions/get-refiners-for-collection', runOn: 0},{name:'searchConfiguration',  path:'modules/search-result-container/actions/get-mapped-search-configuration', runOn: 0}],
        
        definitionPath: 'src/modules/search-result-container/search-result-container.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'search-result-container',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/search-result-container'
    });
            

    isNotRegistered('wkea') && (binding.modules['wkea'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/themes/wkea/wkea'),
            {
                chunkName: () => 'partner-themes-wkea-wkea',
                ignoreBabelRename: true
            }
        ),
        $type: 'themeModule',
        dataActions: [],
        definitionExtensions: ['buybox'],
        definitionPath: 'src/themes/wkea/wkea.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        themeSettings: 'wkea.theme.settings.json',
        moduleDirectory: 'src/themes/wkea'
    });
            

    isNotRegistered('wkea-about') && (binding.modules['wkea-about'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-about/wkea-about'),
            {
                chunkName: () => 'partner-modules-wkea-about-wkea-about',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-about/wkea-about.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-about',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-about'
    });
            

    isNotRegistered('wkea-account') && (binding.modules['wkea-account'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-account/wkea-account'),
            {
                chunkName: () => 'partner-modules-wkea-account-wkea-account',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-account/wkea-account.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-account',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-account'
    });
            

    isNotRegistered('wkea-culture') && (binding.modules['wkea-culture'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-culture/wkea-culture'),
            {
                chunkName: () => 'partner-modules-wkea-culture-wkea-culture',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-culture/wkea-culture.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-culture',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-culture'
    });
            

    isNotRegistered('wkea-guess') && (binding.modules['wkea-guess'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-guess/wkea-guess'),
            {
                chunkName: () => 'partner-modules-wkea-guess-wkea-guess',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-guess/wkea-guess.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-guess',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-guess'
    });
            

    isNotRegistered('wkea-history') && (binding.modules['wkea-history'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-history/wkea-history'),
            {
                chunkName: () => 'partner-modules-wkea-history-wkea-history',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-history/wkea-history.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-history',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-history'
    });
            

    isNotRegistered('wkea-introduction') && (binding.modules['wkea-introduction'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-introduction/wkea-introduction'),
            {
                chunkName: () => 'partner-modules-wkea-introduction-wkea-introduction',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-introduction/wkea-introduction.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-introduction',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-introduction'
    });
            

    isNotRegistered('wkea-service') && (binding.modules['wkea-service'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-service/wkea-service'),
            {
                chunkName: () => 'partner-modules-wkea-service-wkea-service',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-service/wkea-service.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-service',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-service'
    });
            

    isNotRegistered('wkea-supplier') && (binding.modules['wkea-supplier'] = {
        component: universal(
            () =>
                import(/* webpackInclude: /.(t|j)sx?$/ */ 
                /* webpackExclude: /.data.|.autogenerated.|.test.|.field.|.data-model./ */
                'partner/modules/wkea-supplier/wkea-supplier'),
            {
                chunkName: () => 'partner-modules-wkea-supplier-wkea-supplier',
                ignoreBabelRename: true
            }
        ),
        $type: 'contentModule',
        dataActions: [],
        
        definitionPath: 'src/modules/wkea-supplier/wkea-supplier.definition.json',
        isNodeModule: false,
        moduleNamespace: '__local__',
        name: 'wkea-supplier',
        packageName: '__local__',
        
        parentDefinitionPath: '',
        
        
        moduleDirectory: 'src/modules/wkea-supplier'
    });
            

        if (isNotRegistered('breadcrumb')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-category-paths';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-category-paths');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('breadcrumb')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('breadcrumb')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-dimensions-for-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-dimensions-for-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-price-for-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-price-for-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-product-availabilities-for-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-product-availabilities-for-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-ratings-summary';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-ratings-summary');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('buybox')) {
            const sanitizedActionPath = '@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/bopis-utilities/dist/lib/store-selector-state-manager/store-selector-state-manager-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-availabilities-cartlines';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-availabilities-cartlines');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-cartlines';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-delivery-options-for-cartlines');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-feature-state';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-feature-state');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-items-in-wishlist';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-items-in-wishlist');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-products-in-active-cart';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-products-in-active-cart');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-wishlist-by-customer-id');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/order-templates/get-order-templates-preview');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/search-org-unit-locations';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/search-org-unit-locations');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('cart')) {
            const sanitizedActionPath = '@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('header')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('header')) {
            const sanitizedActionPath = '@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('index-person-information')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-customer');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('index-person-information')) {
            const sanitizedActionPath = '@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce/global-state/dist/lib/data-actions/cart-state-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('index-product')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-simple-products';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-simple-products');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('media-gallery')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-media-locations-by-id';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-media-locations-by-id');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('media-gallery')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('navigation-menu')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-categories-hierarchy';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-categories-hierarchy');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/search-utilities/dist/lib/search-state-data-action';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/search-utilities/dist/lib/search-state-data-action');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-current-category-hierarchy');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = '@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant';
            binding.dataActions[sanitizedActionPath] = require('@msdyn365-commerce-modules/retail-actions/dist/lib/get-selected-variant');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = 'modules/search-result-container/actions/get-full-products-by-collection';
            binding.dataActions[sanitizedActionPath] = require('partner/modules/search-result-container/actions/get-full-products-by-collection');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = 'modules/search-result-container/actions/get-mapped-search-configuration';
            binding.dataActions[sanitizedActionPath] = require('partner/modules/search-result-container/actions/get-mapped-search-configuration');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = 'modules/search-result-container/actions/get-refiners-for-collection';
            binding.dataActions[sanitizedActionPath] = require('partner/modules/search-result-container/actions/get-refiners-for-collection');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

        if (isNotRegistered('search-result-container')) {
            const sanitizedActionPath = 'modules/search-result-container/list-page-state';
            binding.dataActions[sanitizedActionPath] = require('partner/modules/search-result-container/list-page-state');
            if (!binding.dataActions[sanitizedActionPath].default) {
                throw new Error('Data action path ' + sanitizedActionPath + ' does not have a default export');
            }
            binding.dataActions[sanitizedActionPath].default.prototype.RegistrationId = sanitizedActionPath;
            if (binding.dataActions[sanitizedActionPath].default.prototype.id) {
                binding.dataActions[binding.dataActions[sanitizedActionPath].default.prototype.id] = sanitizedActionPath;
            }
        }
            

    
    } catch (e) {
        handleError('-', e);
    }
    
    return binding;
};