/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaIntroductionData } from './wkea-introduction.data';
import { IWkeaIntroductionProps } from './wkea-introduction.props.autogenerated';

export interface IWkeaIntroductionViewProps extends IWkeaIntroductionProps<IWkeaIntroductionData> {

}

/**
 *
 * WkeaIntroduction component
 * @extends {React.PureComponent<IWkeaIntroductionProps<IWkeaIntroductionData>>}
 */
class WkeaIntroduction extends React.PureComponent<IWkeaIntroductionProps<IWkeaIntroductionData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaIntroduction;
