/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaDocumentData } from './wkea-document.data';
import { IWkeaDocumentProps } from './wkea-document.props.autogenerated';

export interface IWkeaDocumentViewProps extends IWkeaDocumentProps<IWkeaDocumentData> {
    wkeaFaq: React.ReactNode
    wkeaIntroduction: React.ReactNode
    wkeaSupplier: React.ReactNode
    wkeaCulture: React.ReactNode
    wkeaWarranty: React.ReactNode
    wkeaAbout: React.ReactNode
}

/**
 *
 * WkeaDocument component
 * @extends {React.PureComponent<IWkeaDocumentProps<IWkeaDocumentData>>}
 */
class WkeaDocument extends React.PureComponent<IWkeaDocumentProps<IWkeaDocumentData>> {
    public render(): JSX.Element | null {
        const {
            slots: {
                wkeaFaq,
                wkeaIntroduction,
                wkeaSupplier,
                wkeaCulture,
                wkeaWarranty,
                wkeaAbout
            }
        } = this.props;
        const viewProps: IWkeaDocumentViewProps = {
            ...this.props,
            wkeaFaq: wkeaFaq && wkeaFaq.length > 0 ? wkeaFaq[0] : undefined,
            wkeaIntroduction: wkeaIntroduction && wkeaIntroduction.length > 0 ? wkeaIntroduction[0] : undefined,
            wkeaSupplier: wkeaSupplier && wkeaSupplier.length > 0 ? wkeaSupplier[0] : undefined,
            wkeaCulture: wkeaCulture && wkeaCulture.length > 0 ? wkeaCulture[0] : undefined,
            wkeaWarranty: wkeaWarranty && wkeaWarranty.length > 0 ? wkeaWarranty[0] : undefined,
            wkeaAbout: wkeaAbout && wkeaAbout.length > 0 ? wkeaAbout[0] : undefined,
        }
        return this.props.renderView(viewProps);
    }
}

export default WkeaDocument;
