/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ITestData } from './test.data';
import { ITestProps } from './test.props.autogenerated';

export interface ITestViewProps extends ITestProps<ITestData> {

}

/**
 *
 * Test component
 * @extends {React.PureComponent<ITestProps<ITestData>>}
 */
class Test extends React.PureComponent<ITestProps<ITestData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Test;
