/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import IndexProduct from '../index-product';
import { IIndexProductData } from '../index-product.data';
import {
  IIndexProductConfig,
  IIndexProductProps
} from '../index-product.props.autogenerated';

const mockData: IIndexProductData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IIndexProductConfig = {
  showText: 'index-product'
};

const mockActions = {};

describe('IndexProduct', () => {
  let moduleProps: IIndexProductProps<IIndexProductData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IIndexProductProps<IIndexProductData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <IndexProduct {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
