/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import IndexNav from '../index-nav';
import { IIndexNavData } from '../index-nav.data';
import {
  IIndexNavConfig,
  IIndexNavProps
} from '../index-nav.props.autogenerated';

const mockData: IIndexNavData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IIndexNavConfig = {
  showText: 'index-nav'
};

const mockActions = {};

describe('IndexNav', () => {
  let moduleProps: IIndexNavProps<IIndexNavData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IIndexNavProps<IIndexNavData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <IndexNav {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
