/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IWkeaCultureData } from './wkea-culture.data';
import { IWkeaCultureProps } from './wkea-culture.props.autogenerated';

export interface IWkeaCultureViewProps extends IWkeaCultureProps<IWkeaCultureData> {

}

/**
 *
 * WkeaCulture component
 * @extends {React.PureComponent<IWkeaCultureProps<IWkeaCultureData>>}
 */
class WkeaCulture extends React.PureComponent<IWkeaCultureProps<IWkeaCultureData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default WkeaCulture;
