/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Footer from '../footer';
import { IFooterData } from '../footer.data';
import {
  IFooterConfig,
  IFooterProps
} from '../footer.props.autogenerated';

const mockData: IFooterData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IFooterConfig = {
  showText: 'footer'
};

const mockActions = {};

describe('Footer', () => {
  let moduleProps: IFooterProps<IFooterData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IFooterProps<IFooterData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Footer {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
