/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IFooterData } from './footer.data';
import { IFooterProps } from './footer.props.autogenerated';

export interface IFooterViewProps extends IFooterProps<IFooterData> {

}

/**
 *
 * Footer component
 * @extends {React.PureComponent<IFooterProps<IFooterData>>}
 */
class Footer extends React.PureComponent<IFooterProps<IFooterData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Footer;
