/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import WkeaGuess from '../wkea-guess';
import { IWkeaGuessData } from '../wkea-guess.data';
import {
  IWkeaGuessConfig,
  IWkeaGuessProps
} from '../wkea-guess.props.autogenerated';

const mockData: IWkeaGuessData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IWkeaGuessConfig = {
  showText: 'wkea-guess'
};

const mockActions = {};

describe('WkeaGuess', () => {
  let moduleProps: IWkeaGuessProps<IWkeaGuessData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IWkeaGuessProps<IWkeaGuessData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <WkeaGuess {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
