/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Demo from '../demo';
import { IDemoData } from '../demo.data';
import {
  IDemoConfig,
  IDemoProps
} from '../demo.props.autogenerated';

const mockData: IDemoData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IDemoConfig = {
  showText: 'demo'
};

const mockActions = {};

describe('Demo', () => {
  let moduleProps: IDemoProps<IDemoData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IDemoProps<IDemoData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <Demo {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
