/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IIndexNavData } from './index-nav.data';
import { IIndexNavProps } from './index-nav.props.autogenerated';

export interface IIndexNavViewProps extends IIndexNavProps<IIndexNavData> {

}

/**
 *
 * IndexNav component
 * @extends {React.PureComponent<IIndexNavProps<IIndexNavData>>}
 */
class IndexNav extends React.PureComponent<IIndexNavProps<IIndexNavData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default IndexNav;
